### ISSUE TITLE
Explain why use ejs

### ISSUE THREAD

**Issue by tried42long** [PresidentDwayneCamacho/Corner#5]
I am having difficulty getting my stuff to be compatible with ejs. Trey, can you briefly explain why we are using ejs instead of normal html?

**Comment by TreyAmador** [comment]
One could change it I think relatively easily.  But for the time being it's easier to allow ejs to connect the user interface with the javascript client side.  It's just a few lines of code to display info into the user interface.  Otherwise, with HTML, AngularJS is the way to go, since it allows you to connect the interface and client side.
So once we move to that, then it's fine.

**Comment by TreyAmador** [comment]
We're using angular now, hahahahaahahahaahahah.
